# Generated by Django 4.1.5 on 2023-01-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_propetytype_property_is_for_rent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_featured',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
