# Generated by Django 4.1.5 on 2023-01-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='is_for_rent',
        ),
        migrations.RemoveField(
            model_name='property',
            name='is_for_sale',
        ),
        migrations.AddField(
            model_name='property',
            name='for_type',
            field=models.CharField(blank=True, choices=[('FOR RENT', 'FOR RENT'), ('FOR SALE', 'FOR SALE')], default='FOR RENT', max_length=250, null=True),
        ),
    ]
